import manifest from './photo-manifest.json';

/**
 * Resolves a venue photo to the pre-built WebP variants in
 * public/photos/opt, generated by scripts/optimize-photos.mjs.
 *
 * These are served as plain static files, deliberately bypassing
 * next/image. On Vercel each (source, width, Accept) combination a visitor
 * requests is billed as an image transformation, and the venue photography
 * never changes — so routing it through the optimizer meant paying, in a
 * slow drip, for a result we can compute once at build time. Firestore dish
 * photos still use next/image: those are uploaded by the admin and can't be
 * pre-built.
 *
 * Keys are the canonical `/photos/<file>.jpeg` paths. No file is served at
 * that path any more — it's an identifier, and every consumer goes through
 * here to get a real URL.
 */

type PhotoEntry = { base: string; widths: number[] };

const PHOTOS = manifest as Record<string, PhotoEntry>;

export type ResolvedPhoto = {
  /** Largest variant — the `src` fallback, and what the lightbox shows */
  src: string;
  srcSet: string;
  width: number;
};

export function resolvePhoto(key: string): ResolvedPhoto | null {
  const entry = PHOTOS[key];
  if (!entry) return null;

  const largest = entry.widths[entry.widths.length - 1];
  return {
    src: `${entry.base}-${largest}.webp`,
    srcSet: entry.widths.map((w) => `${entry.base}-${w}.webp ${w}w`).join(', '),
    width: largest,
  };
}

/** True for keys this module can serve — i.e. local venue photography. */
export const isLocalPhoto = (src: string) => src in PHOTOS;
